import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="w-full h-full">
      <body
        className={inter.className}
        class="w-full h-full"
        style={{
          backgroundImage: `url(https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg)`,
        }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
